<?php

/**
 * Costcenter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     MSc. Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Costcenter extends BaseCostcenter {

    public static function getMaxDeep() {
        $q = Doctrine_Query::create()
                ->select('MAX(t.path)')
                ->from('Costcenter t');
        $array = $q->fetchOne()->toArray();

        return count(split('/', $array['MAX'])) - 1;
    }

    public function isUsed() {
        return $this->getAccounts()->count() > 0;

        $result = $this->getAccounts()->count() > 0;

        $costcenters = $this->getCostcenters();
        foreach ($costcenters as $costcenter)
            $result = $result || $costcenter->isUsed();

        return $result;
    }

    public function isChildOf($parent) {
        $costcenter = $this;

        do {
            if ($costcenter->getParentid() != NULL && ($costcenter->getId() != $parent->getId()))
                $costcenter = Doctrine::getTable('Costcenter')->find($costcenter->getParentid());
        }
        while ($costcenter->getParentid() != NULL && ($costcenter->getId() != $parent->getId()));

        if ($costcenter->getId() == $parent->getId())
            return true;

        return false;
    }

}