<?php

/**
 * Currency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     MSc. Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Currency extends BaseCurrency {

    public function isUsed() {
        return $this->getTransactions()->count() > 0;
    }

}