<?php

/**
 * ElementElementRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElementElementRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElementElementRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElementElementRelation');
    }
}