<?php

/**
 * UmUmRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UmUmRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UmUmRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UmUmRelation');
    }
}